project_id: 597731
base_path: .
base_url: https://api.crowdin.com
preserve_hierarchy: true

files:
  - source: 'web-vue/src/locales/zh/*.js'
    type: js
    translation: 'web-vue/src/locales/%two_letters_code%/%original_file_name%'
    escape_quotes: 3
    escape_special_characters: 0
    ignore:
      - index.js

  - source: 'modules/server/src/main/resources/i18n/message_zh.properties'
    type: properties
    translation: '%original_path%/message_%two_letters_code%.properties'

  - source: 'modules/agent/src/main/resources/i18n/message_zh.properties'
    type: properties
    translation: '%original_path%/message_%two_letters_code%.properties'
