version: '3.8'
services:
  server:
    image: jpomdocker/jpom:server-${JPOM_VERSION}
    build:
      dockerfile: ./modules/server/Dockerfile
      context: .
      args:
        JPOM_VERSION: ${JPOM_VERSION}
    environment:
      "jpom.authorize.token": ${SERVER_TOKEN}
    volumes:
      - jpom-server-data:/usr/local/jpom-server/data
      - jpom-server-log:/usr/local/jpom-server/log
    ports:
      - "2122:2122"
volumes:
  jpom-server-data:
  jpom-server-log:
