#运行端口号
server:
  port: 2123
  servlet:
    session:
      timeout: 1H
      cookie:
        name: JPOMID-AGENT
spring:
  application:
    name: jpomAgent
  servlet:
    multipart:
      # 上传文件大小限制 12KB -- parses as 12 kilobytes 5MB  -- parses as 5 megabytes 20  -- parses as 20 kilobytes
      max-request-size: 2GB
      max-file-size: 1GB
banner:
  msg: Jpom-Agent Starting
# 启动完成自动初始化指定包
preload:
  packageName: io.jpom.system.init
# 强制去掉空格
request:
  trimAll: true
  urlDecode: true
