version: '1.0'
name: pipeline-20220528
displayName: docker-hub
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - dev
    tags:
      prefix:
        - v
stages:
  - name: stage-1b917201
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: buildx
        hostGroupID: gitee-go
        script: |-
          # 请在此输入您想执行的脚本
          echo 'Hello Gitee!'
          # 服务端
          docker buildx build --platform linux/amd64,linux/arm64 -t jpomdocker/jpom:2.8.22 -f ./modules/server/DockerfileRelease --push .
          #
          docker buildx build --platform linux/amd64,linux/arm64 -t jpomdocker/jpom:latest -f ./modules/server/DockerfileRelease --push .
        strategy:
          retry: '0'
permissions:
  - role: admin
    members: []
