name: crowdin

on:
  push:
    branches: [ dev, i18n ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  sync-crowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          auto_approve_imported: true
          download_translations: true
          localization_branch_name: 'i18n/crowdin-sync'
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_labels: 'i18n'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'dev'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
